# This is a basic workflow to help you get started with Actions

name: proxy-pool-check

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # 定时任务
    - cron: '0/30 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - run: chmod  777 ./proxypoolCheck
      - run: ls -l
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
        
          sudo -E apt-get update
          sudo -E apt-get -y install wget unzip 
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: execute proxy-pool-check
        run: ./proxypoolCheck -c config.yaml
      - name: download proxies file 
        run: wget http://127.0.0.1:90/clash/proxies  -O proxies
#       - name: 提交更改
#       run: |                 
#          git config --local user.email "jth445600@gmail.com"
#          git config --local user.name "jth445600"
#          git add subscribe/v2ray.txt
#          git add subscribe/clash.yml
#          git commit -m "更新订阅链接"
#       - name: 推送更改
#       uses:  ad-m/github-push-action@master
#       with:
#          # github_token: ${{ secrets.TOKEN }}
#          branch: main
