# This is a basic workflow to help you get started with Actions

name: proxy-pool-check

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # 定时任务
    - cron: '50 22 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - run: chmod  777 ./proxypoolCheck
      - run: ls -l
      # - name: Space cleanup
      #   env:
      #     DEBIAN_FRONTEND: noninteractive
      #   run: |
        
      #     sudo -E apt-get update
      #     sudo -E apt-get -y install wget unzip 
      #     sudo -E apt-get -y autoremove --purge
      #     sudo -E apt-get clean
      - name: execute proxy-pool-check
        run: |
          rm -f check-log
          touch check-log
            # wget wispy-thunder-b2f5.aaron123abc.workers.dev -O heroku-zhenhe > ./check-log 2>&1
          #sudo -E ./proxypoolCheck -c config.yaml  >> ./check-log 2>&1 &
      - name: download proxies file 
        run: |

            git clone https://github.com/pojiezhiyuanjun/freev2.git  >> ./check-log 2>&1
            touch freev2.txt
            ls freev2/ | awk '{print "https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/"$0}'  > freev2.txt
            git clone https://github.com/JACKUSR2089/v2ray-subscribed.git >> ./check-log 2>&1
            touch freev3.txt
            ls v2ray-subscribed/subscribed/ | awk '{print "https://raw.githubusercontent.com/JACKUSR2089/v2ray-subscribed/master/subscribed/"$0}'  >  freev3.txt
          
      - name: 提交更改
        run: |                 
         git config --local user.email "temp1@445600.ga"
          git config --local user.name "Laurence8866"
          git add freev2.txt
          git add freev3.txt
          git commit -m "更新订阅链接"
          git push 
        # - name: 推送更改
        # uses:  ad-m/github-push-action@master
        # with:
        #  # github_token: ${{ secrets.TOKEN }}
        #  branch: main
